# -*- coding: utf-8 -*-
"""
__init__.py (템플릿)

이 파일은 자동으로 생성되는 Blender 애드온의 초기화 모듈이다. 애드온을 등록할 때
클래스 목록을 Blender에 등록하고, 해제할 때 역순으로 해제한다. bl_info 사전은
Blender가 애드온 목록에서 이 애드온을 식별하고 설명을 표시하는 데 사용된다.

본 애드온은 IDS(XML)에서 파생된 ids_cache.json 파일을 통해 오브젝트에 필요한
Pset.Property를 생성하고, 지오메트리 기반 자동채움(method=b)을 수행한다. 검증
또는 리포트 출력과 같은 추가 기능은 포함하지 않는다.
"""

bl_info = {
    "name": "IDS Auto Addon (Generated)",
    "author": "Generated by generator",
    "version": (0, 1, 0),
    "blender": (4, 5, 0),
    "location": "View3D > Sidebar > IDS",
    "description": "IDS 캐시(ids_cache.json) 기반으로 Pset.Property 생성 및 자동채움(b) 기능을 제공한다",
    "category": "Object",
}

import bpy
from . import parser, methods, ops, ui

# Blender에 등록해야 하는 클래스들을 정의한다. 등록 순서는 보통 오퍼레이터부터
# 패널 순이다. register()와 unregister() 함수에서 이 목록을 순회한다.
classes = (
    ops.IDS_OT_create_props,
    ops.IDS_OT_autofill_props,
    ui.IDS_PT_panel,
)


def register():
    """애드온을 Blender에 등록한다."""
    for cls in classes:
        bpy.utils.register_class(cls)


def unregister():
    """애드온을 Blender에서 해제한다."""
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)